name: Build and Deploy to App Runner

on:
  pull_request:
    branches: [main]

env:
  AWS_REGION: ap-southeast-1
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG .
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG

      - name: Update App Runner service
        run: |
          aws apprunner update-service \
            --service-arn "$APP_RUNNER_SERVICE_ARN" \
            --source-configuration "ImageRepository={
            ImageIdentifier=\"$ECR_REPOSITORY_URI:$IMAGE_TAG\",
            ImageRepositoryType=\"ECR\"
            }"
