name: Build and Deploy to App Runner

on:
  pull_request:
    branches: [main]

env:
  AWS_REGION: ap-southeast-1

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-output.outputs.image_tag }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        id: set-output
        run: echo "image_tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ steps.set-output.outputs.image_tag }} .
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ steps.set-output.outputs.image_tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update App Runner service
        run: |
          aws apprunner update-service \
            --service-arn "$APP_RUNNER_SERVICE_ARN" \
            --source-configuration "ImageRepository={ImageIdentifier=$ECR_REPOSITORY_URI:${{ needs.build.outputs.image_tag }},ImageRepositoryType=ECR}"
        env:
          APP_RUNNER_SERVICE_ARN: ${{ secrets.APP_RUNNER_SERVICE_ARN }}
          ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
